sources:
  - GeistPixel.glyphspackage
axisOrder:
  - ELSH
familyName: Geist Pixel
cleanUp: true
buildVariable: True
outputDir: ../fonts/GeistPixel
stat:
  - name: Element Shape
    tag: ELSH
    values:
    - name: Regular
      value: 0
      flags: 2
    - name: Circle
      value: 40
    - name: Grid
      value: 60
    - name: Triangle
      value: 80
    - name: Line
      value: 100